version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/bonds
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bonds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
